import "./styles/global.scss";
import "./styles/colors.scss";
import "./styles/layout.scss";
import "./styles/components.scss";
import "./styles/animations.scss";
import "./styles/forms.scss";

import localFont from "next/font/local";
import { Nav, Footer } from "@/lib/components";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ducimain = localFont({
  src: [
    {
      path: "./ducimain-bold.woff",
      weight: "bold",
      style: "normal",
    },
    {
      path: "./ducimain-bold.woff2",
      weight: "bold",
      style: "normal",
    },
    // Intentionally setting medium font to weight normal. CRA version of the site does this.
    {
      path: "./ducimain-medium.woff",
      weight: "normal",
      style: "normal",
    },
    {
      path: "./ducimain-medium.woff2",
      weight: "normal",
      style: "normal",
    },
  ],
  variable: "--font-ducimain",
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={ducimain.variable}>
      <body>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
